// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN39hZLkxzVvtEVqnUfH4fG3NzrL6FdiU',
    appId: '1:672229652411:web:0704169eb4821cb534f69e',
    messagingSenderId: '672229652411',
    projectId: 'spacexplorer-e2f45',
    authDomain: 'spacexplorer-e2f45.firebaseapp.com',
    storageBucket: 'spacexplorer-e2f45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhofLT7k4EXJ7egX-WTv4Dmp6fmUEkRZw',
    appId: '1:672229652411:android:963b89ec1bd6299f34f69e',
    messagingSenderId: '672229652411',
    projectId: 'spacexplorer-e2f45',
    storageBucket: 'spacexplorer-e2f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0xnPhd_z6XpyPrY2TxpDRzH4899eCj-c',
    appId: '1:672229652411:ios:6b16df81cb62360f34f69e',
    messagingSenderId: '672229652411',
    projectId: 'spacexplorer-e2f45',
    storageBucket: 'spacexplorer-e2f45.appspot.com',
    iosClientId: '672229652411-rqds49qqjpvvb12aavvfqo60mb89tb5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.isrospaceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0xnPhd_z6XpyPrY2TxpDRzH4899eCj-c',
    appId: '1:672229652411:ios:6b16df81cb62360f34f69e',
    messagingSenderId: '672229652411',
    projectId: 'spacexplorer-e2f45',
    storageBucket: 'spacexplorer-e2f45.appspot.com',
    iosClientId: '672229652411-rqds49qqjpvvb12aavvfqo60mb89tb5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.isrospaceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN39hZLkxzVvtEVqnUfH4fG3NzrL6FdiU',
    appId: '1:672229652411:web:e1b44e90a9e71d8c34f69e',
    messagingSenderId: '672229652411',
    projectId: 'spacexplorer-e2f45',
    authDomain: 'spacexplorer-e2f45.firebaseapp.com',
    storageBucket: 'spacexplorer-e2f45.appspot.com',
  );

}